version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gitnet-postgres
    environment:
      POSTGRES_USER: gitnet
      POSTGRES_PASSWORD: gitnetpass
      POSTGRES_DB: gitnetdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: gitnet-backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgres://gitnet:gitnetpass@gitnet-postgres:5432/gitnetdb
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - .env

volumes:
  pgdata:
